services:
  # Base de datos PostgreSQL para Smile Hub
  smile-hub-db:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    container_name: smile-hub-db-container
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PGSQL_PORT_PUBLIC}:5432
    volumes:
      - smile-hub-pg-data:/var/lib/postgresql/data
    networks:
      smile-hub-network:
        ipv4_address: 171.21.0.251
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  smile-hub-adminer:
    image: adminer
    container_name: smile-hub-adminer-container
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - smile-hub-db
    networks:
      smile-hub-network:
        ipv4_address: 171.21.0.253

  smile-hub-pgadmin:
    container_name: smile-hub-pgadmin-container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@smilehub.org"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - 16543:80
    depends_on:
      - smile-hub-db
    networks:
      smile-hub-network:
        ipv4_address: 171.21.0.254

networks:
  smile-hub-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 171.21.0.0/24

volumes:
  smile-hub-pg-data:
    name: smile-hub-data-local
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${LOCAL_DATA_DIR_BD}